name: CI

on: [push, pull_request]

jobs:
  test:
    name: 'Test'

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node: [13.x, 12.x, 10.x, 8.x]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Lint
      run: npm run lint
      
    - name: Test
      run: npm test
      
    - name: Run quadra on quadra!
      uses: Raul6469/quadra-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: 0.1.2-rc.2
